import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
const suisse = localFont({
  src: "./fonts/fonts.woff2",
  variable: "--font-suisse",
  weight: "100 900",
});
const suisseMedium = localFont({
  src: "./fonts/fonts.woff2",
  variable: "--font-suisseMedium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${suisse.variable} ${suisseMedium.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
